name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ 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 }}
          USERNAME: ${{ LeeJaeJun1 }}
      - name: Commit & Push
        run: |
          git config LeeJaeJun1
          git config jj030207@naver.com
          git add -A .
          git commit -m "generated"
          git push
